architect.zip -> architects.tgz

diff --git a/bin/minecraft b/bin/minecraft
--- a/bin/minecraft
+++ b/bin/minecraft
@@ -37,15 +37,15 @@ function create_sandbox(){
 	archdir="${tmc_root}/architect"
 	if test ! -d "${archdir}"; then
 		mkdir "${archdir}"
-		if test which wget >/dev/null 2>&1; then
-			echo "getting https://raw.github.com/turenar/teketo-mclauncher/master/architects.zip"
-			wget -O "${tmc_root}/architects.zip" https://raw.github.com/turenar/teketo-mclauncher/master/architects.zip
+		if which wget >/dev/null 2>&1; then
+			echo "getting https://github.com/turenar/teketo-mclauncher/raw/master/architects.tgz..."
+			wget -O "${tmc_root}/architects.tgz" https://github.com/turenar/teketo-mclauncher/raw/master/architects.tgz || echo 'failed wget'
 		else
 			echo 'command "wget" is not found' >&2
 			exit 2
 		fi
 		pushd ${tmc_root} >/dev/null 2>&1
-		jar -xf architects.zip
+		tar -zxf architects.tgz || ( echo 'failed tar -zxf'; exit 3 )
 		popd >/dev/null 2>&1
 	fi
 
